[package]
name = "transaction"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
wallet = { path = "../wallet" }
bs58 = "0.5.1"
chrono = "0.4"
uuid = { version = "1.3", features = ["v4"] }